name: plant_triplet_net
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.10
  - anaconda=custom
  - anaconda-client=1.6.5
  - anaconda-navigator=1.6.9
  - anaconda-project=0.8.0
  - asn1crypto=0.22.0
  - astroid=1.5.3
  - astropy=2.0.2
  - babel=2.5.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.6.0
  - bitarray=0.8.1
  - bkcharts=0.2
  - blas=1.1
  - blaze=0.11.3
  - bleach=2.0.0
  - blosc=1.15.1
  - bokeh=0.12.10
  - boto=2.48.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.14.12
  - certifi=2019.3.9
  - cffi=1.10.0
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.4.0
  - clyent=1.2.2
  - colorama=0.3.9
  - conda-verify=2.0.0
  - contextlib2=0.5.5
  - cryptography=2.5
  - curl=7.63.0
  - cycler=0.10.0
  - cython=0.26.1
  - cytoolz=0.8.2
  - dask=0.15.3
  - dask-core=0.15.3
  - datashape=0.5.4
  - dbus=1.13.2
  - decorator=4.1.2
  - distributed=1.19.1
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - fastcache=1.0.2
  - ffmpeg=4.1
  - filelock=2.0.12
  - flask=0.12.2
  - flask-cors=3.0.3
  - fontconfig=2.13.1
  - freetype=2.9.1
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=1.2.2
  - giflib=5.1.4
  - glib=2.56.2
  - glob2=0.5
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gnutls=3.6.5
  - graphite2=1.3.10
  - greenlet=0.4.12
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - harfbuzz=1.9.0
  - hdbscan=0.8.22
  - hdf5=1.10.4
  - heapdict=1.0.0
  - html5lib=0.999999999
  - icu=58.2
  - idna=2.6
  - imageio=2.2.0
  - imagesize=0.7.1
  - intel-openmp=2018.0.0
  - ipykernel=4.6.1
  - ipython=6.1.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.0.0
  - isort=4.2.15
  - itsdangerous=0.24
  - jasper=1.900.1
  - jbig=2.1
  - jdcal=1.3
  - jedi=0.10.2
  - jinja2=2.9.6
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.1.0
  - jupyter_console=5.2.0
  - jupyter_core=4.3.0
  - jupyterlab=0.27.0
  - jupyterlab_launcher=0.4.0
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - lazy-object-proxy=1.3.1
  - libcurl=7.63.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.13
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.29
  - llvmlite=0.26.0
  - locket=0.2.0
  - lxml=4.1.0
  - lzo=2.10
  - mahotas=1.4.5
  - markupsafe=1.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - mccabe=0.6.1
  - mistune=0.7.4
  - mkl=2018.0.0
  - mkl-service=1.1.2
  - mpc=1.0.3
  - mpfr=3.1.5
  - mpmath=0.19
  - msgpack-python=0.4.8
  - multipledispatch=0.4.9
  - navigator-updater=0.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.0
  - ninja=1.8.2
  - nltk=3.2.4
  - nose=1.3.7
  - notebook=5.0.0
  - numba=0.41.0
  - numexpr=2.6.9
  - numpy=1.13.3
  - numpydoc=0.7.0
  - odo=0.5.1
  - olefile=0.44
  - openblas=0.3.3
  - opencv=3.4.4
  - openh264=1.8.0
  - openpyxl=2.4.8
  - openssl=1.1.1b
  - packaging=16.8
  - pandas=0.24.1
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - pango=1.40.14
  - partd=0.3.8
  - path.py=10.3.1
  - pathlib2=2.3.0
  - patsy=0.4.1
  - pcre=8.42
  - pep8=1.7.0
  - pexpect=4.2.1
  - pickleshare=0.7.4
  - pillow=5.4.1
  - pip=9.0.1
  - pixman=0.34.0
  - pkginfo=1.4.1
  - ply=3.10
  - prompt_toolkit=1.0.15
  - psutil=5.4.0
  - pthread-stubs=0.4
  - ptyprocess=0.5.2
  - py=1.4.34
  - pycodestyle=2.3.1
  - pycosat=0.6.2
  - pycparser=2.18
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pylint=1.7.4
  - pyodbc=4.0.17
  - pyopenssl=17.2.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.7
  - pytables=3.4.4
  - pytest=3.2.1
  - python=3.6.8
  - python-dateutil=2.6.1
  - pytorch=0.4.1
  - pytz=2017.2
  - pywavelets=0.5.2
  - pyyaml=3.12
  - pyzmq=16.0.2
  - qt=5.6.3
  - qtawesome=0.4.4
  - qtconsole=4.3.1
  - qtpy=1.3.1
  - readline=7.0
  - requests=2.18.4
  - rope=0.10.5
  - ruamel_yaml=0.11.14
  - scikit-image=0.13.0
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - seaborn=0.8.0
  - setuptools=36.5.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.18.1
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sortedcollections=0.5.3
  - sortedcontainers=1.5.7
  - sphinx=1.6.3
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - spyder=3.2.4
  - sqlalchemy=1.1.13
  - sqlite=3.26.0
  - statsmodels=0.8.0
  - sympy=1.1.1
  - tblib=1.3.2
  - terminado=0.6
  - testpath=0.3.1
  - tk=8.6.9
  - toolz=0.8.2
  - torchvision=0.2.1
  - tornado=4.5.2
  - traitlets=4.3.2
  - typing=3.6.2
  - umap-learn=0.3.8
  - unicodecsv=0.14.1
  - unixodbc=2.3.4
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.12.2
  - wheel=0.29.0
  - widgetsnbextension=3.0.2
  - wrapt=1.10.11
  - x264=1!152.20180717
  - xlrd=1.1.0
  - xlsxwriter=1.0.2
  - xlwt=1.3.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.2
  - zict=0.1.3
  - zlib=1.2.11
